import { Hour } from "@/api";

export const mockHours: Hour[] = [
  {
    created_at: "10/28/24",
    date_completed: "10/28/24",
    email: "emilymlewis0@gmail.com",
    event_id: 2,
    has_event: true,
    hours: 1,
    id: 1,
    is_approved: true,
    shift_id: 3,
  },
  {
    created_at: "10/28/24",
    date_completed: "10/28/24",
    email: "emilymlewis0@gmail.com",
    event_id: 2,
    has_event: true,
    hours: 1,
    id: 2,
    is_approved: true,
    shift_id: 3,
  },
  {
    created_at: "10/28/24",
    date_completed: "10/28/24",
    email: "emilymlewis0@gmail.com",
    event_id: null,
    has_event: false,
    hours: 1,
    id: 3,
    is_approved: true,
    shift_id: 3,
  },
  {
    created_at: "10/28/24",
    date_completed: "10/28/24",
    email: "emilymlewis0@gmail.com",
    event_id: 2,
    has_event: true,
    hours: 1,
    id: 4,
    is_approved: false,
    shift_id: 3,
  },
  {
    created_at: "10/28/24",
    date_completed: "10/28/24",
    email: "emilymlewis0@gmail.com",
    event_id: 2,
    has_event: true,
    hours: 1,
    id: 5,
    is_approved: false,
    shift_id: 3,
  },
  {
    created_at: "10/28/24",
    date_completed: "10/28/24",
    email: "emilymlewis0@gmail.com",
    event_id: 2,
    has_event: true,
    hours: 1,
    id: 6,
    is_approved: false,
    shift_id: 3,
  },
  {
    created_at: "10/28/24",
    date_completed: "10/28/24",
    email: "emilymlewis0@gmail.com",
    event_id: 2,
    has_event: true,
    hours: 1,
    id: 7,
    is_approved: false,
    shift_id: 3,
  },
  {
    created_at: "10/28/24",
    date_completed: "10/28/24",
    email: "emilymlewis0@gmail.com",
    event_id: 2,
    has_event: true,
    hours: 1,
    id: 8,
    is_approved: false,
    shift_id: 3,
  },
  {
    created_at: "10/28/24",
    date_completed: "10/28/24",
    email: "emilymlewis0@gmail.com",
    event_id: 2,
    has_event: true,
    hours: 1,
    id: 9,
    is_approved: false,
    shift_id: 3,
  },
  {
    created_at: "10/28/24",
    date_completed: "10/28/24",
    email: "emilymlewis0@gmail.com",
    event_id: 2,
    has_event: true,
    hours: 1,
    id: 10,
    is_approved: false,
    shift_id: 3,
  },
  {
    created_at: "10/28/24",
    date_completed: "10/28/24",
    email: "emilymlewis0@gmail.com",
    event_id: 2,
    has_event: true,
    hours: 1,
    id: 11,
    is_approved: false,
    shift_id: 3,
  },
];
